package mil.darpa.vande.legacy.graphserver;

import java.util.ArrayList;
import java.util.List;

import mil.darpa.vande.DirectableObject;
import mil.darpa.vande.legacy.entity.IdProperty;
/**
 * XXX: Why are we using custom hashcode and equals?  Use autogenerated ones.
 * @author ??
 *
 */

@Deprecated
public class TransactionDistinctEntityPair implements DirectableObject {

	private List<Object> attributeList = new ArrayList<Object>();
	private String dest = "";
	private String destEntityId = "";
	private String destEntityName = "";
	private int nbr = 0;
	private String src = "";

	private String srcEntityId = "";
	private String srcEntityName = "";

	private Double total = 0D;

	//TODO: This was changed to Number, from String, to make it work with Vande.  But does this suit the needs? --djue
	private Number value = 0;

	private int weight = 0;

	public TransactionDistinctEntityPair() {

	}

	public void addAttribute(Object attr) {
		attributeList.add(attr);
	}

	/**
	 * This was changed so it overrides the equals(Object) instead of inheriting
	 * it as a covariant of equals(TransactionDistinctEntityPair). This was
	 * labeled by findbugs as scary. --djue
	 */
	public boolean equals(Object o) {
		if (o instanceof TransactionDistinctEntityPair) {
			TransactionDistinctEntityPair t = (TransactionDistinctEntityPair) o;
			if (!src.equals(t.getSrc()))
				return false;
			if (!dest.equals(t.getDest()))
				return false;
			return true;
		}
		return false;
	}

	public List<Object> getAttributeList() {
		return attributeList;
	}

	@Override
	public String getDest() {
		// TODO Auto-generated method stub
		return dest;
	}

	@Override
	public List<Object> getDestAttributes() {
		// TODO Auto-generated method stub
		return null;
	}

	public String getDestEntityId() {
		return destEntityId;
	}

	public String getDestEntityName() {
		return destEntityName;
	}

	@Override
	public List<Object> getEdgeAttributes() {
		return attributeList;
	}

	@Override
	public String getId() {
		// TODO Auto-generated method stub
		return null;
	}

	public int getNbr() {
		return nbr;
	}

	@Override
	public String getSrc() {
		return src;
	}

	@Override
	public List<Object> getSrcAttributes() {
		// TODO Auto-generated method stub
		return null;
	}

	public String getSrcEntityId() {
		return srcEntityId;
	}

	public String getSrcEntityName() {
		return srcEntityName;
	}

	public Double getTotal() {
		return total;
	}

	@Override
	public Number getValue() {
		return value;
	}

	@Override
	public int getWeight() {
		return weight;
	}

	public int hashCode() {
		return (src + dest).hashCode();
	}

	public void setAttributeList(List<Object> attributeList) {
		this.attributeList = attributeList;
	}

	public void setDest(String dest) {
		this.dest = dest;
	}

	public void setDestEntityId(String destEntityId) {
		this.destEntityId = destEntityId;
	}

	public void setDestEntityName(String destEntityName) {
		this.destEntityName = destEntityName;
	}

	public void setNbr(int nbr) {
		this.nbr = nbr;
	}

	public void setSrc(String src) {
		this.src = src;
	}

	public void setSrcEntityId(String srcEntityId) {
		this.srcEntityId = srcEntityId;
	}

	public void setSrcEntityName(String srcEntityName) {
		this.srcEntityName = srcEntityName;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	public void setValue(Number value) {
		this.value = value;
	}

	public void setWeight(int weight) {
		this.weight = weight;
	}

}
